generated: '2026-07-11'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: portal.azure.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Jan  5 19:53:18 2027 GMT
  hsts: true
  hsts_max_age: 31536000
- host: docs.microsoft.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Dec 10 06:59:10 2026 GMT
  hsts: true
  hsts_max_age: 31536000
- host: management.azure.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Nov  8 23:36:21 2026 GMT
  hsts: null
domains:
- domain: azure.com
  dnssec: false
  caa:
  - 0 contactemail "caarecordaware@microsoft.com"
  spf: true
  dmarc: true
  dmarc_policy: none
- domain: microsoft.com
  dnssec: false
  caa:
  - 0 contactemail "caarecordaware@microsoft.com"
  spf: true
  dmarc: true
  dmarc_policy: reject
